version: '2'
services:
  cardoc-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/carDoc/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=carDoc
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
